ARG VERSION
FROM almalinux:${VERSION:-8}
ARG course="DEVOPS" \ 
    trainer="SivaAnna" \
    duration="10hrs"
RUN echo "COURSE: ${course},TRAINER: ${trainer},DURATION: ${duration}"
CMD ["sleep","1000"]